apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: task-management-platform-ui
  description: UI application
  annotations:
    github.com/project-slug: SuyogWani/task-management-platform/frontend
spec:
  type: website
  lifecycle: staging
  owner: suyog_wani
