namespace:
  name: task-management-platform

backend:
  service:
    port: 5005

frontend:
  replicaCount: 1
  image:
    repository: docker.io/wanisuyog/task-management-platform
    tag: frontend-2.0.0
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
    nodePort: 30080