apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    app: backend
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.backend.secret.dbPassword | quote }}
  JWT_SECRET: {{ .Values.backend.secret.jwtSecret | quote }}
