apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app: backend
data:
  DB_HOST: {{ .Values.backend.env.dbHost | quote }}
  DB_PORT: {{ .Values.backend.env.dbPort | quote }}
  DB_USER: {{ .Values.backend.env.dbUser | quote }}
  DB_NAME: {{ .Values.backend.env.dbName | quote }}
