---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: task-management-platform
spec:
  encryptedData:
    DB_PASSWORD: AgAG+5heo84LrQckahypGmBKQfUMMf9hy4EnY44nfcwTBI0sg/D+oBUqhFVV1oMP7pho+0mwVn3glyyCIMSFD3ZWbP2QB/AWbe7nXqW8CTiNE4LXFf3Ix3K55ixYC0kPoOOWKOrBFdNLS1d3s8lNDk1Jnq2hypW+Phv/cjs1B6E7p0PLkj13MFPZ1KkCKCxBkm8QbLN354lM4R3n3z6YPgn2SoBaraUl/lHZTbPf51YGBtSiXW+Aw6PFrdpJQUX9//928o6AyDhhlP6oDgfGOmF7+hdVHpt/8u5MmPoM3Uns92AOup5y2oQNi3KYiFDnVKEdfH4gk/oG9tQHIqt5Mz6VE0BbTMlA8dXGk1JLJkf7pDToUQH9Gq0Sx3l7KXqDUXMPaGZwqDiD4W5Atyr/Q5UZz0QdJYlAJDM6e2dcCpoAWwMl7wMwfp/ZYz8Q72SDRqkHnG74mB5zY6KXO33oNx1qje1plzoALSe/SXmqF9jmvlOHpPabcgUhmzgtWpSS0b4Gv0kJUI/sOw9/CLtXLI6eWLebJFYzSd7dcS2o4wIEjKHJ01l4+tVdKXUpETjslrs6MJGsdv9DNgAQv3dkSb3ycCW2jS7NhF9DR+XPA70hLBgEu+4wdJJi124zuCcuPHy3I0mpeXna5689VZw5I1kGonELTSgCVguUhrRMGSb+ZlbEu48nUJIjTAblumzIo+FbwyrZWqr+sA==
    JWT_SECRET: AgCqmOdHS4tKrxUqUocFySqdyc7Q3ScRSPlxJby3Ybie6mcL4xMs9qytRuMvxLezjAUb/7GthJCwUYQt9SfvQ5Y3pwgqS76K6v7/oh5PbFL+5/3vmjx3J1yYguK9eK4VOveBFcS1vABMpD5Eq3j0M8fWyWsrCt217aTw/1lZKYJMbGGrV3FVTleiL3zF/xPKlw0VQ36W2qhlS2878GzR+qn16xQS8SVqpfhVr7sTYKiMfRMJX1cdekaSf+IcaRZ/JgNMMmah/OBzlh7+WuXxpiBpVfzVesOBTQQHOtddnoj3ViWtfsbVOguaAN/xZyUXgFcaPpynwMP8tXIdK1IyFCch71R0VqJTrVzwZNDofSxO0wBjEpYpkTtduB4O5eEW9MORVL+MJgn8jQkD/FIKRn1uoqab86VOb6Bd6wyW52DdZSQHtRhH+LXC6bqiQWsxTypY8sOAChSIPEgq8Ju66zAiMb4RyxJm2B50POXdrKJAfQtxHyjui5g7QdLRI9C5uwEhQb6rgJZlH30VvZlXobTTxK6Qk90u/RQDwm88bsnmBbpEtC+Mrn4ofuUPfxIapQWP8AQRsTh4YBSm4tdue7Rbj3WWmJTk/dMcXXx2mpjEdwXq+dnrRPKk/EtxhKHTD8HXoRq1zDUNIGmD8CfWZm0p8JcwbFK2QESDW64Q4lyj1f9LJ5TmQdvJIT3YFW+CyvQ=
  template:
    metadata:
      labels:
        app: backend
      name: backend-secret
      namespace: task-management-platform
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: task-management-platform
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgC5cJeM1I0YE/bWUNcHW/JgjaA0Tgz90HTf2qsPtjpqv5F0z/ZKphEdKSBri3vRl8D1gdAiuuWzG7b5kZEmIDsIT9J8CqOWqFMRCA/I6RjnINO3k9bUbIyfx5bq/WnXYqAaxOxNr3a3Klu/4HzpeIEBhtAN+BlOYmRFT16YGsAiryzTUnNo/23sfXjum1Ybh/2a20y2NlkzsYJyBH/AO6sFKRwEPbTPsp/R+wx/oEQFni3lagZqeotHGyu2Q3JIsMF/g+H6ATOAz89qAe0ctoqsfJLKEYFw0nnw3d2fIzaEzun0TQRj21IbMlGw07Q/AW0KEc53OOdLRUzbrTzyZQ9dQFlYL2mkvq89tNbIqM+J6j6D5p76kqSLkrJVSPZQJ6FtKGKwPPyTls7q89w2QFIYJ7A9PLuv86zU94QzsdySOvKrJt6ziVfoZaUtYTXOGpPApx6Lv7rwaB8ysZab53YvcJ5jiAEWk8OIWeSW+GdKxtG2C0myR0OLspdIFZP2zH/dVGr8xVg8gkKulqocVx39EGNY8+nzWkktRJDAdKkZwVnnaSNUz6aKJL4c1s8vZaEwzY4E+mo0iOaq25iV+U+NxAg6v0IsJfPEfee8aywpK+I29cVKTu6ZcmAVp7W89hAKsgCQo4+entNO00afoYze8qgisBdlFKXiB7RDdCgXRkb/AFjHNGUv5ELtRVgyncglRi7gLLGAtg==
  template:
    metadata:
      labels:
        app: postgres
      name: postgres-secret
      namespace: task-management-platform
    type: Opaque
