apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
