namespace:
  name: task-management-platform

backend:
  replicaCount: 1
  image:
    repository: docker.io/wanisuyog/task-management-platform
    tag: backend-2.0.0
    pullPolicy: IfNotPresent
  service:
    port: 5005
  env:
    dbHost: postgres
    dbPort: "5432"
    dbUser: postgres
    dbName: task_manager